#!/bin/bash
# Autor: Lara Maia <lara@craft.net.br>
# Versão: 0.3
IFS=$(echo -en "\n\b")

if [ `id -u` == 0 ]; then geany $@; fi

function root_open() {
	export geany_params=${@}
	export geany_user=mrk3004
	export geany_confpath=/home/${geany_user}/.config/geany
	gksudo -m "Digite sua senha" geany ${geany_params}
	gksudo 'chown -R ${geany_user} ${geany_confpath}'
	for file in ${geany_params}; do
		if [ "`cat "$file"`" == "" ]; then
			gksudo 'rm -f "'$file'"'
		fi
	done
	unset geany_params geany_user geany_confpath
}

function user_open() {
	export geany_params=${@}
	geany ${geany_params}
	for file in ${geany_params}; do
		if [ "`cat "$file"`" == "" ]; then
			rm -f $file
		fi
	done
	unset geany_params
}

for file in ${@}; do
	if [ ! -f "$file" ]; then
		touch "$file" 2>/dev/null
		if [ $? != 0 ]; then
			root_open "${@}" & exit 0
		fi
	fi
	if [ `ls -l "$file" | awk '{print $4}'` == root ]; then
		root_open "${@}" & exit 0
	fi
done

user_open "${@}" & exit 0
